name: Build prod

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Reason'
        required: true
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: production
    steps:
    - name: Build docker image
      uses: appleboy/ssh-action@v1.0.3
      with:
        # Private Key
        key: ${{ secrets.SSH_KEY }}
        # Remote host
        host: ${{ secrets.SSH_HOST }}
        # Remote user
        username: ${{ secrets.SSH_USERNAME }}
        script: |
          cd approbado-server
          git pull
          docker build -t approbado-server .
          docker run -p 80:3000 approbado-server
