name: Build prod

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Reason'
        required: true
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: production
    steps:
    - name: Build docker image
      uses: appleboy/ssh-action@v1.0.3
      with:
        key: ${{ secrets.SSH_KEY }}
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        script: |
          set -e
          cd approbado-server
          git pull
          docker build -t approbado-server .
          docker ps -q --filter "name=approbado-server" | grep -q . && docker stop approbado-server
          docker ps -aq --filter "name=approbado-server" | grep -q . && docker rm approbado-server
          docker run -d -p 80:4000 approbado-server
