# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js + pm2 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: production
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Node.js + pm2 ${{ matrix.node-version }}
      uses: appleboy/ssh-action@v0.1.5
      with:
        # Private Key
        key: ${{ secrets.SSH_KEY }}
        # Remote host
        host: ${{ secrets.SSH_HOST }}
        # Remote user
        username: ${{ secrets.SSH_USERNAME }}
    - name: Build server
      working-directory: /root/server
      run: | 
        cd server
        git pull
        npm i
        npm run build
        pm2 restart all
