# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js + pm2 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Node.js + pm2 ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
        key: ${{secrets.SSH_KEY}} # Private or public key of the server
        username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
    - run: npm i
    - run: npm run build --if-present
    - run: pm2 restart all
